
Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.box_version = "8.8.0"
  config.vm.boot_timeout = 600
  #config.vm.network "private_network", ip: "192.168.0.30"
  config.vm.provision "ansible", run: "always" do |ansible|
   ansible.playbook = "playbook.yml"
 end
end
